version: '3.0'


services:
  #-------------------------------------------------------------------------------
  # Web interface
  #-------------------------------------------------------------------------------
  web:
    build: ./web
    container_name: web
    ports:
      - "5000:5000"
    environment:
      - rfcsearch
    depends_on:
      - elasticsearch
      - bertserving
    networks:
      - shared-network

  #-------------------------------------------------------------------------------
  # Elastic Search
  #-------------------------------------------------------------------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    tty: true
    environment:
      discovery.type: single-node
    networks:
      - shared-network

  #-------------------------------------------------------------------------------
  # Bert-as-a-service
  #-------------------------------------------------------------------------------
  bertserving:
    build: ./bertserving
    container_name: bertserving
    ports:
      - "5555:5555"
      - "5556:5556"
    environment:
      - PATH_MODEL=${PATH_MODEL} #./_models/netbert
    volumes:
      - "${PATH_MODEL}:/model"
    networks:
      - shared-network

volumes:
  es-data:
    driver: local

networks:
  shared-network:
